// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxUZ27fg5Hn7NadQh8-i0-8s9lKLnjjNM',
    appId: '1:80844618230:web:fb345c60b2e1e395e72fd7',
    messagingSenderId: '80844618230',
    projectId: 'my-note-app-2ec50',
    authDomain: 'my-note-app-2ec50.firebaseapp.com',
    storageBucket: 'my-note-app-2ec50.firebasestorage.app',
    measurementId: 'G-VRD7M0W8P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvqNutCDNYoScXpgWY8_kOk1qOG7AFOjk',
    appId: '1:80844618230:android:4b9863b0742c46eee72fd7',
    messagingSenderId: '80844618230',
    projectId: 'my-note-app-2ec50',
    storageBucket: 'my-note-app-2ec50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhTjZd_Y8P9pVBFM0wvr6CMSWUBCnHTlU',
    appId: '1:80844618230:ios:28570f23ac3b83abe72fd7',
    messagingSenderId: '80844618230',
    projectId: 'my-note-app-2ec50',
    storageBucket: 'my-note-app-2ec50.firebasestorage.app',
    androidClientId: '80844618230-rnvqs0bgkmf6e8bs26um5kunrakb7h0j.apps.googleusercontent.com',
    iosClientId: '80844618230-rhmipvtqbfb5rjk8n309pr5cst85kg4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

}